version: '3'
services:
  phase1-dev:
    build: .
    container_name: phase1-dev
    ports:
      - "8501:8501"
    env_file: .env.dev
    volumes:
      - .:/app
    restart: always
    

  phase1-prod:
    build: .
    container_name: phase1-prod
    ports:
      - "8502:8501"
    env_file: .env.prod
    restart: always
    
